version: "3.1"

services:
  
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: deviavir/zenbot:unstable
    volumes:
      - ./simulations/:/app/simulations/
      - ./conf.js:/app/conf.js:ro
    restart: always
    tty: true
    ports:
      - "17365:17365"
    depends_on:
      - mongodb
    environment:
      - ZENBOT_MONGODB_HOST=mongodb
      - MONGODB_PORT_27017_TCP_ADDR=mongodb
    stdin_open: true

  mongodb:
    image: mongo:latest
    #ports:
      #- "27017:27017"
    volumes:
      - ./database:/data/db
    #command: mongod --bind_ip=0.0.0.0 --logpath=/dev/null

  adminmongo:
    image: mrvautin/adminmongo
    links:
      - mongodb
    tty: true
    ports:
      - "127.0.0.1:1234:1234"
    environment:
      - CONN_NAME=zenbot_mongodb
      - DB_HOST=mongodb
      - DB_PORT=27017
      - HOST=0.0.0.0
    command: "npm start"
